version: '2.4'

services:
  database:
    container_name: 'AIRMON_database'
    restart: unless-stopped
    image: postgres:12
    volumes:
      - ./database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=apidb
    ports:
      - '5432'
    networks: 
      - private_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d apidb -U admin -h 0.0.0.0 -p 5432"]
      interval: 30s
      timeout: 20s
      retries: 3

  backend:
    container_name: 'AIRMON_backend'
    restart: unless-stopped
    build:
      context: './Backend'
      dockerfile: 'Dockerfile'
    volumes:
        - ./Backend:/go/src/airmon
    depends_on:
        database:
          condition: service_healthy
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=apidb
      - ADDRESS=airmon.ufp.pt
    ports:
      - '88'
    networks:
      - private_network
      - public_network
    
  frontend:
    container_name: 'AIRMON_frontend'
    restart: unless-stopped
    build:
      context: './Frontend'
      dockerfile: 'Dockerfile'
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '89'
    networks: 
      - public_network

volumes:
  database-data:

networks:
    public_network:
        driver: host
    private_network:
        driver: host